version: '3.8'

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb,sqs
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - "./entrypoint.sh:/etc/localstack/init/ready.d/entrypoint.sh"

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - localstack

  worker:
    build:
      context: ./worker
    depends_on:
      - localstack
